// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Badge } from "./badge.slint";
import { MaterialPalette } from "../styling/material_palette.slint";
import { MaterialStyleMetrics } from "../styling/material_style_metrics.slint";
import { MaterialText } from "./material_text.slint";
import { MaterialTypography } from "../styling/material_typography.slint";
import { ExtendedTouchArea } from "./extended_touch_area.slint";
import { StateLayer, Ripple } from "./state_layer.slint";
import { Icon } from "./icon.slint";
import { NavigationItem } from "../items/navigation_item.slint";
import { BaseNavigationItemTemplate, BaseNavigation } from "./base_navigation.slint";
import { ActiveIndicator } from "./active_indicator.slint";
import { MaterialAnimations } from "../styling/material_animations.slint";

export component NavigationItemTemplate inherits BaseNavigationItemTemplate {
    property <bool> has_icon: root.icon.width > 0 && root.icon.height > 0;
    property <bool> has_selected_icon: root.selected_icon.width > 0 || root.selected_icon.height > 0;
    property <color> icon_color: root.selected ? MaterialPalette.on_secondary_container : MaterialPalette.on_surface_variant;
    property <color> text_color: root.selected ? MaterialPalette.on_surface : MaterialPalette.on_surface_variant;

    animate icon_color {
        duration: MaterialAnimations.standard_decelerate_duration;
        easing: MaterialAnimations.emphasized_easing;
    }
    animate text_color {
        duration: MaterialAnimations.standard_decelerate_duration;
        easing: MaterialAnimations.emphasized_easing;
    }

    in property <length> navitem_padding_top: MaterialStyleMetrics.padding_12;
    in property <length> navitem_padding_bottom: MaterialStyleMetrics.padding_16;

    property <bool> r0_active: false;
    property <length> r0_x;
    property <length> r0_y;
    property <bool> r0_pressed: false;

    property <bool> r1_active: false;
    property <length> r1_x;
    property <length> r1_y;
    property <bool> r1_pressed: false;

    function trigger_ripple(x: length, y: length) {
        if !root.r0_active {
            root.r0_x = x; root.r0_y = y; root.r0_pressed = true; root.r0_active = true;
        } else if !root.r1_active {
            root.r1_x = x; root.r1_y = y; root.r1_pressed = true; root.r1_active = true;
        }
    }

    function release_ripples() {
        root.r0_pressed = false;
        root.r1_pressed = false;
    }

    Rectangle {
        width: 100%;
        height: 100%;
    }

    touch_area := ExtendedTouchArea {
        pointer-event(event) => {
            if event.button == PointerEventButton.left && !root.selected {
                if event.kind == PointerEventKind.down {
                    root.trigger_ripple(self.mouse-x, self.mouse-y);
                } else if event.kind == PointerEventKind.up || event.kind == PointerEventKind.cancel {
                    root.release_ripples();
                }
            }
        }

        changed pressed => {
            if !self.pressed {
                root.release_ripples();
            }
        }

        changed enter_pressed => {
            if self.enter_pressed && !root.selected {
                root.trigger_ripple(root.width / 2, root.height / 2);
            } else if !self.enter_pressed {
                root.release_ripples();
            }
        }

        HorizontalLayout {
            alignment: center;

            VerticalLayout {
                alignment: start;
                spacing: MaterialStyleMetrics.spacing_4;
                padding_top: root.navitem_padding_top;
                padding_bottom: root.navitem_padding_bottom;

                HorizontalLayout {
                    alignment: center;

                    background_layer := Rectangle {
                        width: max(MaterialStyleMetrics.size_64, state_layout.min_width);
                        height: max(MaterialStyleMetrics.size_32, state_layout.min_height);
                        border_radius: self.height / 2;

                        ActiveIndicator {
                            active: root.selected;
                        }

                        state_layer := StateLayer {
                            background: root.icon_color;
                            border_radius: parent.border_radius;
                            enabled: true;
                            has_focus: touch_area.has_focus;
                            has_hover: touch_area.has_hover;
                            pressed: touch_area.pressed || touch_area.enter_pressed;
                            width: 100%;
                            height: 100%;

                            if root.r0_active : Ripple {
                                pressed: root.r0_pressed && !root.selected;
                                width: 100%;
                                height: 100%;
                                border_radius: parent.border_radius;
                                pressed_x: root.r0_x;
                                pressed_y: root.r0_y;
                                color: root.icon_color;
                                finished => {
                                    root.r0_active = false;
                                }
                            }

                            if root.r1_active : Ripple {
                                pressed: root.r1_pressed && !root.selected;
                                width: 100%;
                                height: 100%;
                                border_radius: parent.border_radius;
                                pressed_x: root.r1_x;
                                pressed_y: root.r1_y;
                                color: root.icon_color;
                                finished => {
                                    root.r1_active = false;
                                }
                            }

                            state_layout := HorizontalLayout {
                                padding_left: MaterialStyleMetrics.padding_20;
                                padding_right: self.padding_left;
                                alignment: center;

                                VerticalLayout {
                                    alignment: center;

                                    if !root.has_icon && !root.has_selected_icon : Rectangle {
                                        width: 12px;
                                        height: self.width;
                                        border_radius: self.width / 2;
                                        background: root.icon_color;
                                    }

                                    if root.has_icon || root.has_selected_icon : Icon {
                                        source: root.icon;
                                        colorize: root.icon_color;

                                        states [
                                            selected when root.selected && root.has_selected_icon : {
                                                source: root.selected_icon;
                                            }
                                        ]
                                    }
                                }
                             }
                        }

                        if root.show_badge || root.badge != "" : Badge {
                            x: parent.width / 2;
                            y: 0;
                            text: root.badge;
                        }
                    }
                }

                label := MaterialText {
                    text: root.text;
                    style: MaterialTypography.label_medium;
                    color: root.text_color;
                    horizontal_alignment: center;
                }
            }
        }

        clicked => {
            root.clicked();
        }
    }

}

export component NavigationBar inherits BaseNavigation {
    min_height: max(MaterialStyleMetrics.size_80, layout.min_height);

    Rectangle {
        background: MaterialPalette.surface_container;

        layout := HorizontalLayout {
            padding_left: MaterialStyleMetrics.padding_8;
            padding_right: self.padding_left;
            spacing: MaterialStyleMetrics.spacing_8;

            for item[index] in root.items : NavigationItemTemplate {
                icon: item.icon;
                selected_icon: item.selected_icon;
                text: item.text;
                index: index;
                selected: index == root.current_index;
                show_badge: item.show_badge;
                badge: item.badge;

                clicked => {
                    root.select(index);
                }
            }
        }
    }
}
